name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Schritt 1: Code aus dem Repo laden
      - name: Check out code
        uses: actions/checkout@v2

      # Schritt 2: Java 17 einrichten (du kannst auch Java 11 oder 8 nehmen)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      # Schritt 3: Gradle-Build
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # Schritt 4: Release-APK als Build-Artefakt hochladen
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MyIconPack-APK
          path: app/build/outputs/apk/release/app-release.apk
