name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Code aus dem Repo auschecken
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Java (JDK 17) einrichten
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3) Android SDK installieren
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: "33.0.0"

      # 4) Gradle über apt installieren
      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      # 5) Build mit System-Gradle statt Wrapper
      - name: Build with Gradle
        run: gradle assembleRelease

      # 6) APK als Artifact hochladen
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyIconPack-APK
          path: app/build/outputs/apk/release/app-release.apk
